### ISSUE TITLE
Fraction of tumour cells > 1?

### ISSUE THREAD

**Issue by amootta** [Wedge-lab/dpclust#25]
Hi there,
Thanks very much for making this very useful package. 
I have a query about the results I am getting from dpclust. It has successfully run on one of my samples, with input that was pre-processed from Battenberg calls. However, I am just looking at the plot and it is showing me that there are mutations clustering with Fraction of Tumor Cells greater than 1. I am not sure what this means and if this means that there is a mistake in the calculation somewhere? 
![1_DirichletProcessplot_with_cluster_locations_2](https://github.com/Wedge-lab/dpclust/assets/32172683/e39784e2-9d3d-48d2-8e2b-d4406655f406)

Thanks very much

**Comment by davidwedge** [comment]
Hi @amootta, thanks for your query. We don't restrict DPClust to call clusters with a CCF between 0 and 1, as individual mutations can have an apparent CCF higher than 1 due to random sampling of mutant and WT DNA fragments. This means that we can have a clonal cluster called with a CCF slightly above (or slightly below) 1. CCF estimates are likely to be less accurate for samples sequenced to lower depths, of low purity or with few mutations. From the figure, I don't know what sequencing depth or purity your sample had, but it appears to have a small number of mutations - is this WGS or WES?

**Comment by amootta** [comment]
Hi @davidwedge  
Thanks so much for getting back to me and for the explanation. You are right that it is from WGS - what is the minimum sequencing depth recommended? Apologies if I missed this information somewhere else. Would you recommend that I still use this software for WGS? Thanks again.
