### ISSUE TITLE
CNV profiles

### ISSUE THREAD

**Issue by aleednn** [Wedge-lab/dpclust#33]
Hi,

I am using DPClust to perform clustering analysis. I was wondering if it's possible to extract CNV profiles for the clusters generated by the analysis. Are there any existing options or parameters that allow for extracting these profiles, or would it be necessary to modify the code to implement this functionality?

Additionally, I would like to clarify how the _cndatafile_ should be structured. Specifically, if I set _co_cluster_cna_ to TRUE, what format and columns should the cndatafile have for it to be correctly interpreted by the pipeline?

Thanks in advance for your help!

**Comment by sdentro** [comment]
Thanks for the message. We did at some point consider co clustering CNAs, but there is no longer any code included in the package to do this. There are considerable challenges with including CNAs due to the frequent parallel evolution occurring in cancers.

What you could do, when you have copy number data where you're convinced this isn't a problem, is to create pseudo-SNVs with appropriate read counts for each CNA. These can then be included in the clustering (just extend the DPClust input file), or assign them separately post-hoc by calculating a likelihood.
